spring.application.name=place-review
# For supporting PUT, PATCH, DELETE in the HTML form
spring.mvc.hiddenmethod.filter.enabled=true
# H2 console setting
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# H2 Driver
spring.datasource.driver-class-name=org.h2.Driver
# Memory DB
spring.datasource.url=jdbc:h2:mem:testdb
# H2 User Setting
spring.datasource.username=sa
spring.datasource.password=
# create, update, validate, none
spring.jpa.hibernate.ddl-auto=update
# It helps SQL formatting
spring.jpa.properties.hibernate.format_sql=true
# Show queries
spring.jpa.show-sql=true
# H2 Dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# For the page developing, false
spring.thymeleaf.cache=false
# This setting's for above
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=500MB
# Where our session's stored
server.servlet.session.tracking-modes=cookie
# Session timeout
server.servlet.session.timeout=20m
# Server Port
server.port=8080
# Logging pattern
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
# Logging level
logging.level.org.springframework.security=trace
# SMTP \uC11C\uBC84 \uD638\uC2A4\uD2B8
spring.mail.host=smtp.gmail.com
# SMTP \uC11C\uBC84 \uD3EC\uD2B8
spring.mail.port=587
# SMTP \uC11C\uBC84 \uB85C\uADF8\uC778 \uACC4\uC815
spring.mail.username=${MAIL_USERNAME}
# STMP \uC11C\uBC84 \uB85C\uADF8\uC778 \uD328\uC2A4\uC6CC\uB4DC
spring.mail.password=${MAIL_PASSWORD}
# REDIS \uC124\uC815
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}
#Google OAuth2
spring.security.oauth2.client.registration.google.client-id = ${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret = ${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope = profile, email
